version: "3"
services:
  app:
    build: .
    ports:
      - "${DEVELOPMENT_PORT}:${DEVELOPMENT_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${DEVELOPMENT_PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
